/**
 * 车辆类型
 */
const VEHICLE_TYPE = {
    VAN: 'VAN',//单车
    TRACTOR: 'TRACTOR',//牵引车
    TRAILER: 'TRAILER'//半挂车

};
const VEHICLE_OPERATION_MODE = {
    OUTSOURCE: 'OUTSOURCE',//外包
    SELF_SUPPORT: 'SELF_SUPPORT',//自营
    OUT_INVITE: 'OUT_INVITE'//外请
};
const VEHICLE_SOURCE = {
    COMPANY: 'COMPANY',//自有
    DEPARTMENT_OF_INFORMATION: 'DEPARTMENT_OF_INFORMATION',//信息部
    CAR_TEAM: 'CAR_TEAM',//车队
    PERSONAL: 'PERSONAL'//个人
};
const LINE_PRICE_TYPE = {
    NORMAL: 'NORMAL',//按趟
    WEIGHT: 'WEIGHT',//计重
    VOLUME: 'VOLUME',//按方
    ALL_DAY: 'ALL_DAY'//包天
};
const DISPATCH_STATUS = {
    UNASSIGNED: 'UNASSIGNED',//待指派
    ASSIGNED: 'ASSIGNED',//已指派
    BY_STATION: 'BY_STATION',//已靠站
    STARTED: 'STARTED',//已发车
    IN: 'IN'//已到达
};
const DISPATCH_PAY_TYPE = {
    SUPPLIER: 'SUPPLIER',//供应商
    DRIVER: 'DRIVER'//司机
};
const AUDIT_STATUS = {
    UNAUDITED: 'UNAUDITED',//未审核
    PASS: 'PASS',//审核通过
    NO_PASS: 'NO_PASS'//审核不通过
};
//新业务客户
const IS_NEW_CUSTOMER = {
    YES:'1', //是
    NO:'0'   //否
};

const ORGANIZATION = {
    HEADQUARTERS: 'HEADQUARTERS',//总部
    AREA: 'AREA',//大区
    PARTITION: 'PARTITION'//分区
};

const WAY_BILL_NATURE = {
    NORMAL: 'false',//正班
    TEMPORARY: 'true'//临时
};

const WAY_BILL_STATUS = {
    IN_TRANSIT: 'IN_TRANSIT',//运输中
    IN: 'IN',//已到达
    SIGNED: 'SIGNED',//已签收
    BEEN_ABANDONED: 'BEEN_ABANDONED'//已作废
};

const SUPPLIER_TYPE = {
    CAR_TEAM: 'CAR_TEAM',//车队
    DEPARTMENT_OF_INFORMATION: 'DEPARTMENT_OF_INFORMATION',//信息部
    PLANTFORM_COMPANY: 'PLANTFORM_COMPANY'//平台公司
};

const EQUIPMENT_SIGN_STATUS = {
    SIGNED: 'SIGNED',//已签收
    WAIT_SIGN: 'WAIT_SIGN'//待签收
};

const LINE_TYPE = {
    ONCE: 'ONCE',//单边
    DOUBLE: 'DOUBLE'//往返
};

const ORDER_ORIGIN = {
    BY_MY_LINE:'BY_MY_LINE', // 来自我的线路
    BY_ORDER_SCHEDULE:'BY_ORDER_SCHEDULE' // 来自排班
}
//我的审批内容
const MY_AUDIT_TYPE = {
    WAYBILL_ADJUSTMENT: 'WAYBILL_ADJUSTMENT',//运单调整
    WAYBILL_VOID: 'WAYBILL_VOID',//运单作废
    ADD_SUPPLIER: 'ADD_SUPPLIER',//新增供应商
    ADD_BLACKLIST: 'ADD_BLACKLIST',//新增黑名单
    ADD_CUSTOMER: 'ADD_CUSTOMER',//新增客户
    ADD_STATION: 'ADD_STATION',//新增站点
    ADD_LINE: 'ADD_LINE',//新增线路
    RECEIVE_PRICE_ADJUSTMENT: 'RECEIVE_PRICE_ADJUSTMENT',//应收价格调整
    PAY_PRICE_ADJUSTMENT: 'PAY_PRICE_ADJUSTMENT',//应付价格调整
    PAY_PRICE_CONFIRM: 'PAY_PRICE_CONFIRM'//应付价格确认
};

/**
 * 外包车辆金额计算
 * @type {{MONTHLY_INTEREST_RATE: number}}
 */
const OUTSOURCE_SUM = {
    MONTHLY_INTEREST_RATE: 0.007, // 外包车辆 月利率 0.7%
    PURCHASE_TAX_AMOUNT_RATIO: 11.7     // 外包车了明细 购置税金额  开票金额/11.7
};

//账单金额状态
const PAYMENT_TYPE = {
    PAYMENT: 'PAYMENT',//已付
    NOT_PAYMENT: 'NOT_PAYMENT',//未付
    NOT_SIGN: 'NOT_SIGN',//未签收
    WITHOUT: 'WITHOUT'//无
};

//付款状态
const PAY_STATUS = {
    NOT_PAYMENT: 'NOT_PAYMENT',//未付款
    OBLIGATION: 'OBLIGATION',//待付款
    PAID: 'PAID',//已付款
    PAYMENT_FAILED: 'PAYMENT_FAILED',//付款失败
};

//操作状态
const OPERATION_STATUS = {
    ADD_AUDIT: 'ADD_AUDIT',//添加审核中
    MODIFY_AUDIT: 'MODIFY_AUDIT',//修改审核中
    DELETE_AUDIT: 'DELETE_AUDIT'//删除审核中
};

//自营模式
const SELF_OPERATION_MODE = {
    SELF_SELF_SUPPORT: 'SELF_SELF_SUPPORT',//普通自营
    SELF_OUTSOURCE: 'SELF_OUTSOURCE'//自营合作
};

//运单异常类型
const EXCEPTION_TYPE = {
    TRAFFIC_JAM: 'TRAFFIC_JAM',//堵车
    ROUND: 'ROUND',//绕行
    AMBLE: 'AMBLE',//缓行
    TRAFFIC_ACCIDENT: 'TRAFFIC_ACCIDENT',//交通事故
    VEHICLE_FAILURE: 'VEHICLE_FAILURE',//车辆故障
    CHECK_CAR: 'CHECK_CAR',//查车
    BAD_WEATHER: 'BAD_WEATHER',//异常天气
    OTHER: 'OTHER'//其它
};
const WAYBILL_EQUIPMENT_TYPE = {
    OIL_CARD: 'OIL_CARD',//油卡
    GPS: 'GPS',//gps
    RECEIPT: 'RECEIPT',//回单
};

const DEDUCTION_STATE = {
    DEDUCTED: 'DEDUCTED',//已扣款
    TO_BE_DEDUCTED: 'SUSPEND_THE_DEDUCTIONS',//暂缓扣款
    NOT_DEDUCTED: 'TO_BE_DEDUCTED',//待扣款
    NO_DEDUCTIONS: 'NO_DEDUCTIONS',//自营车不扣款
};

const OIL_CARD_KIND = {
    VEHICLE: 'VEHICLE',//车辆
    USER: 'USER',//用户
    DRIVER: 'DRIVER',//司机
    SUPPILER: 'SUPPILER',//车队
    ORGCODE: 'ORGCODE',//组织
};

const OIL_CANCELLATION = {
    EMPLOY:'EMPLOY',//使用
    INVALID:'INVALID'//作废
};

const ETC_STATUS={
    IN_USE:'IN_USE',//使用
    LOSE_CARD:'LOSE_CARD',//挂失
};
const ETC_CLAIMED_STATUS={
    CLAIMED:'CLAIMED',//已认领
    UN_CLAIM:'UN_CLAIM',//待认领
};

const BACK_LOG_STATUS ={
    UNDISPOSED:'UNDISPOSED',
    BEING_PROCESSED:'BEING_PROCESSED',
    PROCESSED:'PROCESSED'
};

const BACKLOG_MAX_TYPE={
    WAYBILL_INVALID:'WAYBILL_INVALID'
};

const WAYBILL_INVALID={
    OUT_INVITE_PREPAYMENT:'OUT_INVITE_PREPAYMENT',
    OUT_INVITE_COD:'OUT_INVITE_COD',
    OIL_CARD_RECHARGE:'OIL_CARD_RECHARGE'
};
const IS_INVOICE={
    INVOICE:'INVOICE',
    UN_INVOICE:'UN_INVOICE'
};

const DATA_SOURCE_TYPE = {
    WEB:'WEB',
    AUTOMATIC:'AUTOMATIC'
};
const OIL_CARD_SUPPLIER_TYPE={
    PLANTFORM_COMPANY:'PLANTFORM_COMPANY',
    HEADQUARTERS:'HEADQUARTERS'
};
const CUSTOMER_ORDER_STATUS = {
    NEW_CREATE:'NEW_CREATE',
    OFFER:'OFFER',
    CONFIRM:'CONFIRM',
    CANCEL:'CANCEL',
};
const IS_PROJECT_CUSTOMER={
    YES:true,
    NO:false,
};
//申请类型
const APPLY_TYPE={
    ELECTRONIC_OIL_CARD:'ELECTRONIC_OIL_CARD',//电子油卡
    MATERIAL_OBJECT_OIL_CARD:'MATERIAL_OBJECT_OIL_CARD',//实物油卡
    ETC:'ETC',
}
// 结算模式
const SETTLEMENT_MODE={
    SELF_SUPPORT:'SELF_SUPPORT', //自营
    SELF_OUTSOURCE:'SELF_OUTSOURCE', // 自营合作
    OUTSOURCE:'OUTSOURCE',//外请
    FINANCIAL_OUTSOURCE:'FINANCIAL_OUTSOURCE',//金融合作
    SELF_CONSTRUCTION:'SELF_CONSTRUCTION',//自营共建
    TRAILER_CONSTRUCTION:'TRAILER_CONSTRUCTION',//甩挂共建
    OUTSOURCE_CONSTRUCTION:'OUTSOURCE_CONSTRUCTION',//合作共建
    CONTRACT_OUT_INVITE:'CONTRACT_OUT_INVITE',//合同外请车
    TEMPORARY_OUT_INVITE:'TEMPORARY_OUT_INVITE',//临时外请车
    LONG_TERM_OUT_INVITE:'LONG_TERM_OUT_INVITE',//长期外请车
}
// 结算模式类型
const SETTLEMENT_MODE_TYPE={
    LONG_TERM_OUT_INVITE:'LONG_TERM_OUT_INVITE',//长期外请车
    NO_LONG_TERM_OUT_INVITE:'NO_LONG_TERM_OUT_INVITE',//非长期外请车
}
export const Constant = {
    SETTLEMENT_MODE_TYPE,
    SETTLEMENT_MODE,
    IS_PROJECT_CUSTOMER,
    VEHICLE_TYPE,
    VEHICLE_OPERATION_MODE,
    VEHICLE_SOURCE,
    LINE_PRICE_TYPE,
    DISPATCH_STATUS,
    DISPATCH_PAY_TYPE,
    AUDIT_STATUS,
    IS_NEW_CUSTOMER,
    OUTSOURCE_SUM,
    ORGANIZATION,
    WAY_BILL_NATURE,
    WAY_BILL_STATUS,
    SUPPLIER_TYPE,
    EQUIPMENT_SIGN_STATUS,
    LINE_TYPE,
    MY_AUDIT_TYPE,
    PAYMENT_TYPE,
    OPERATION_STATUS,
    PAY_STATUS,
    SELF_OPERATION_MODE,
    EXCEPTION_TYPE,
    WAYBILL_EQUIPMENT_TYPE,
    DEDUCTION_STATE,
    OIL_CARD_KIND,
    OIL_CANCELLATION,
    ETC_STATUS,
    ETC_CLAIMED_STATUS,
    BACK_LOG_STATUS,
    IS_INVOICE,
    DATA_SOURCE_TYPE,
    CUSTOMER_ORDER_STATUS,
    ORDER_ORIGIN,
    OIL_CARD_SUPPLIER_TYPE,
    APPLY_TYPE
};

export default Constant
